name: EAST_SINUS_2024_R_env
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - r-base>=4.2
  - r-essentials>=4.2
  - r-devtools>=2.4
  - r-readr>=2.1
  - r-mice>=3.14
  - r-miceadds>=3.13
  - r-mitools>=2.4
  - r-survival>=3.6
  - r-lme4>=1.1
  - r-broom.mixed>=0.2.9
  - r-magrittr>=2.0
  - r-dplyr>=1.1
  - r-forcats>=1.0
  - r-haven>=2.5
  - r-nricens>=1.6
  - r-ggplot2>=3.5
  - r-tableone>=0.13
  - r-writexl>=1.5
  - r-gt>=0.9.0
  - r-pROC>=1.18
